title: "Gagan's Blog"
description: >
   Posts on Engineering, Culture and Productivity
email: gagan93gtbit@gmail.com
name: 'Gagandeep Singh'
author: 'Gagandeep Singh'
logo: "https://avatars.githubusercontent.com/u/13852061"
float_logo: true

cover: "/assets/images/cover.jpg"
author_image: "https://avatars.githubusercontent.com/u/13852061"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate:	10
url: "https://gagan93.me"
baseurl: "/blog/"
permalink: /:year/:month/:day/:title.html
social:
  - icon:	linkedin
    url:	https://in.linkedin.com/in/gagan93
    desc: LinkedIn
  - icon:	github
    url:	https://github.com/gagan93jtg
    desc:	Github
